language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - if [[ $(rustup show active-toolchain) == stable* ]]; then rustup component add rustfmt; fi;
  - if [[ $(rustup show active-toolchain) == stable* ]]; then rustup component add clippy; fi;

script:
  - if [[ $(rustup show active-toolchain) == stable* ]]; then cargo fmt -- --check; fi;
  - if [[ $(rustup show active-toolchain) == stable* ]]; then cargo clippy -- -D clippy; fi;
  - cargo test --verbose
